version: '3.7'
services:
  nginx:
    image: nginx
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - 8080:80
  php:
    build:
      context: ./docker/build/php
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    links:
      - pgsql
    volumes:
      - ./:/var/www/html
      - ./docker/build/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /var/www/html
  pgsql:
    image: postgres
    ports:
      - 5434:5432
  node:
    image: node
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
